version: 2
updates:
  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
      day: monday
      time: "02:20"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
